<?php require '/var/www/task/task2/views/header.phtml' ?>

<div class="title">
    <h1>List All</h1>
</div>
<div class="text-right">
    <a href="/" class="btn btn-info text-right">Back</a>
</div>

<?php if ($this->pagination['items']) { ?>
    <?php foreach ($this->pagination['items'] as $item) { ?>
        <div class="col-md-12 item">
            <div class="col-md-6">
                <a href="/edit-item?id=<?= $item->getId() ?>"><?= $item->getTitle() ?></a>
            </div>
            <div class="col-md-6">
                <a href="/edit-item?id=<?= $item->getId() ?>" class="btn btn-warning">Edit</a>
            </div>
        </div>
    <?php } ?>

    <div class="pagination text-center">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-2">
                    <?php if (isset($this->pagination['first'])) { ?>
                        <a href="/list-all?page=<?= $this->pagination['first'] ?>"><</a>
                    <?php } ?>
                </div>
                <div class="col-md-2">
                    <?php if (isset($this->pagination['previous'])) { ?>
                        <a href="/list-all?page=<?= $this->pagination['previous'] ?>"><?= $this->pagination['previous'] ?></a>
                    <?php } ?>
                </div>
                <div class="col-md-2">
                    <?php if (isset($this->pagination['current'])) { ?>
                        <?= $this->pagination['current'] ?>
                    <?php } ?>
                </div>
                <div class="col-md-2">
                    <?php if (isset($this->pagination['next'])) { ?>
                        <a href="/list-all?page=<?= $this->pagination['next'] ?>"><?= $this->pagination['next'] ?></a>
                    <?php } ?>
                </div>
                <div class="col-md-2">
                    <?php if (isset($this->pagination['last'])) { ?>
                        <a href="/list-all?page=<?= $this->pagination['last'] ?>">></a>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
<?php } else { ?>
    <h4>There are no items to display.</h4>
<?php } ?>

<?php require '/var/www/task/task2/views/footer.phtml' ?>
